service: github-backup

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${opt:region, 'us-east-2'}
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 7

functions:
  backup:
    iamRoleStatementsName: gh-backup-permissions
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource: 'arn:aws:s3::*:${ssm:/gh-backup/bucket}/*'
      - Effect: 'Allow'
        Action:
          - ssm:GetParametersByPath
        Resource: 'arn:aws:ssm:${self:provider.region}:*:parameter/gh-backup*'
      - Effect: 'Allow'
        Action:
          - kms:Decrypt
        Resource: 'arn:aws:kms:${self:provider.region}:*:key/*'
    handler: src/index.backup
    environment:
      TZ: UTC
    events:
      - schedule: rate(7 days)

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline-scheduler
