service: github-backup
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: ${opt:profile, 'default'}
  region: ${opt:profile, 'us-east-2'}
  memorySize: 256
  timeout: 300
  logRetentionInDays: 7

functions:
  backup:
    handler: index.backup
    events:
      - schedule: rate(3 minutes)
